#!/usr/bin/env bash
# Offer to install the conductor background service. The unit itself
# (systemd on Linux, launchd on macOS) is generated by the binary — this script
# only handles the prompt, then delegates to `<binary> service install`.
#
# Usage: service.sh <binary-path> <config-dir>
# Prompts first (reads /dev/tty). Set CONDUCTOR_INSTALL_SERVICE=yes|no to
# skip the prompt (the legacy PASEO_CONDUCTOR_INSTALL_SERVICE name is still
# honored if set).
set -euo pipefail

default_bin() {
  if [ -f "$HOME/.local/bin/paseo-conductor" ] && [ ! -f "$HOME/.local/bin/conductor" ]; then
    echo "$HOME/.local/bin/paseo-conductor"
  else
    echo "$HOME/.local/bin/conductor"
  fi
}

BIN="${1:-$(default_bin)}"

ask() {
  local ans="${CONDUCTOR_INSTALL_SERVICE:-${PASEO_CONDUCTOR_INSTALL_SERVICE:-}}"
  if [ -z "$ans" ]; then
    if [ -r /dev/tty ]; then
      printf 'Install the conductor background service now? [Y/n] ' >/dev/tty
      read -r ans </dev/tty || ans=""
    fi
    [ -z "$ans" ] && ans="yes" # default: yes
  fi
  case "$ans" in n | N | no | NO) return 1 ;; *) return 0 ;; esac
}

if ! ask; then
  echo "Skipped service install. Start manually with: $BIN run"
  echo "(run '$BIN service install' anytime to set it up.)"
  exit 0
fi

exec "$BIN" service install
