#!/usr/bin/env bash
# Offer to install the paseo-conductor background service. The unit itself
# (systemd on Linux, launchd on macOS) is generated by the binary — this script
# only handles the prompt, then delegates to `paseo-conductor service install`.
#
# Usage: service.sh <binary-path> <config-dir>
# Prompts first (reads /dev/tty). Set PASEO_CONDUCTOR_INSTALL_SERVICE=yes|no to
# skip the prompt.
set -euo pipefail

BIN="${1:-$HOME/.local/bin/paseo-conductor}"

ask() {
  local ans="${PASEO_CONDUCTOR_INSTALL_SERVICE:-}"
  if [ -z "$ans" ]; then
    if [ -r /dev/tty ]; then
      printf 'Install the paseo-conductor background service now? [Y/n] ' >/dev/tty
      read -r ans </dev/tty || ans=""
    fi
    [ -z "$ans" ] && ans="yes" # default: yes
  fi
  case "$ans" in n | N | no | NO) return 1 ;; *) return 0 ;; esac
}

if ! ask; then
  echo "Skipped service install. Start manually with: $BIN run"
  echo "(run '$BIN service install' anytime to set it up.)"
  exit 0
fi

exec "$BIN" service install
